name: festivalapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_secure_storage: any
  provider: ^6.1.5
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  daum_postcode_search: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  

fonts:
  - family: NotoSansKR
    fonts:
      - asset: assets/fonts/NotoSansKR-ExtraLight.ttf
        weight: 100
      - asset: assets/fonts/NotoSansKR-Thin.ttf
        weight: 200
      - asset: assets/fonts/NotoSansKR-Light.ttf
        weight: 300
      - asset: assets/fonts/NotoSansKR-Regular.ttf
        weight: 400
      - asset: assets/fonts/NotoSansKR-Medium.ttf
        weight: 500
      - asset: assets/fonts/NotoSansKR-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/NotoSansKR-Bold.ttf
        weight: 700
      - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/NotoSansKR-Black.ttf
        weight: 900